import type { ExperienceMode } from '@creator/shared';
import { modeSystemPrompt } from '@creator/prompts';
import { ModelRouter } from './router.js';

export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

export async function generateProjectFiles(input: {
  router: ModelRouter;
  mode: ExperienceMode;
  idea: string;
  context: Record<string, unknown>;
}): Promise<GeneratedFile[]> {
  const result = await input.router.complete(
    [
      {
        role: 'system',
        content: `${modeSystemPrompt(input.mode)}
You generate production-ready TypeScript/Next.js application files.
Return a fenced json block: { "files": [{ "path", "content", "language" }] }
Include README.md with Why-architecture section. Keep file count focused for MVP (8-20 files).`,
      },
      {
        role: 'user',
        content: `Idea:\n${input.idea}\n\nApproved plan context:\n${JSON.stringify(input.context, null, 2)}`,
      },
    ],
    'coder',
    input.mode,
  );

  const fenced = result.content.match(/```json\s*([\s\S]*?)```/);
  if (fenced?.[1]) {
    try {
      const parsed = JSON.parse(fenced[1]) as { files?: GeneratedFile[] };
      if (parsed.files?.length) return parsed.files;
    } catch {
      // fall through to scaffold
    }
  }

  return offlineScaffold(input.idea, input.context);
}

function offlineScaffold(idea: string, context: Record<string, unknown>): GeneratedFile[] {
  const name = slugify(String((context.prd as { name?: string } | undefined)?.name ?? 'creator-app'));
  return [
    {
      path: 'README.md',
      language: 'markdown',
      content: `# ${name}

> Generated by Creator — Build Software Like a Senior Engineer.

## Idea
${idea}

## Why this architecture?
- Clear separation between web UI, API, and data.
- Typed contracts reduce runtime surprises.
- Mentoring docs travel with the code so beginners learn the "why".

## Security considerations
- Validate all inputs at the boundary.
- Never trust client-provided user ids for authorization.

## Performance considerations
- Index foreign keys.
- Avoid N+1 queries via Prisma includes.

## Tradeoffs
- Monolith-first for speed; extract services only with evidence.

## Next step
- Run locally, then add authz tests.
`,
    },
    {
      path: 'package.json',
      language: 'json',
      content: JSON.stringify(
        {
          name,
          private: true,
          scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            lint: 'echo \"lint\"',
          },
          dependencies: {
            next: '^15.2.0',
            react: '^19.0.0',
            'react-dom': '^19.0.0',
          },
        },
        null,
        2,
      ),
    },
    {
      path: 'app/page.tsx',
      language: 'typescript',
      content: `export default function HomePage() {
  return (
    <main>
      <h1>${name}</h1>
      <p>Built with Creator mentoring workflow.</p>
    </main>
  );
}
`,
    },
    {
      path: 'app/layout.tsx',
      language: 'typescript',
      content: `import type { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    },
    {
      path: 'docs/ARCHITECTURE.md',
      language: 'markdown',
      content: `# Architecture

## Overview
This MVP uses a modular monolith suitable for early product velocity.

## Diagram
\`\`\`mermaid
flowchart LR
  User --> Web
  Web --> API
  API --> DB[(PostgreSQL)]
\`\`\`

## Why
Fewer moving parts until traffic and team size justify distribution.
`,
    },
    {
      path: 'docker-compose.yml',
      language: 'yaml',
      content: `services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
`,
    },
    {
      path: '.github/workflows/ci.yml',
      language: 'yaml',
      content: `name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
`,
    },
  ];
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 48) || 'creator-app';
}
